import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync, rmSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { resolve, join } from 'node:path';
import { randomBytes } from 'node:crypto';
import { spawn, spawnSync } from 'node:child_process';
import { once } from 'node:events';
import { chromium } from 'playwright-core';

const dir = mkdtempSync(join(tmpdir(), 'habra-cloudflare-test-'));
const config = join(dir, 'wrangler.json'); const state = join(dir, 'state');
const base = 'http://127.0.0.1:8790';
const env = { ...process.env, XDG_CONFIG_HOME: join(dir, 'config'), WRANGLER_SEND_METRICS: 'false', CI: 'true', HABRA_WRANGLER_CONFIG: config, HABRA_D1_PERSIST_TO: state };
const wrangler = resolve('node_modules/wrangler/bin/wrangler.js');
const run = args => { const result = spawnSync(process.execPath, args, { env, encoding: 'utf8', timeout: 60_000 }); if (result.error) throw result.error; assert.equal(result.status, 0, result.stderr + result.stdout); return result.stdout; };
const sql = command => run([wrangler, 'd1', 'execute', 'habra-trainer', '--local', '--config', config, '--persist-to', state, '--command', command, '--json']);
const content = JSON.parse(readFileSync('docs/content/trainer.json', 'utf8'));
const password = 'Local-test-password-172!';
const pause = ms => new Promise(resolve => setTimeout(resolve, ms));
async function eventually(read, expected) {
  for (let i = 0; i < 200; i++) { if (JSON.stringify(await read()) === JSON.stringify(expected)) return; await pause(50); }
  assert.deepEqual(await read(), expected);
}
let server, browser, log = '';
writeFileSync(config, JSON.stringify({ name: 'habra-test', main: resolve('worker/index.ts'), compatibility_date: '2026-10-06', assets: { directory: resolve('docs'), binding: 'ASSETS', run_worker_first: true }, d1_databases: [{ binding: 'DB', database_name: 'habra-trainer', database_id: 'local-habra-test', migrations_dir: resolve('worker/migrations') }], vars: { APP_URL: base } }));
writeFileSync(join(dir, '.dev.vars'), `PASSWORD_PEPPER=${randomBytes(32).toString('hex')}\n`, { mode: 0o600 });
function client() {
  return { cookie: '', csrf: '', async request(path, input, expected = 200, headers = {}) {
    const response = await fetch(base + '/api' + path, { method: input === undefined ? 'GET' : 'POST', headers: { Cookie: this.cookie, ...(input === undefined ? {} : { Origin: base, 'Content-Type': 'application/json', 'X-CSRF-Token': this.csrf }), ...headers }, body: input === undefined ? undefined : JSON.stringify(input) });
    const value = await response.json(); assert.equal(response.status, expected, JSON.stringify(value));
    const cookie = response.headers.get('Set-Cookie'); if (cookie) { assert.match(cookie, /HttpOnly; SameSite=Lax/); this.cookie = cookie.split(';')[0]; }
    if (value.csrfToken) this.csrf = value.csrfToken;
    return value;
  } };
}
try {
  run([wrangler, 'd1', 'migrations', 'apply', 'habra-trainer', '--local', '--config', config, '--persist-to', state]);
  run(['--experimental-strip-types', 'scripts/seed-database.ts', '--local']);
  server = spawn(process.execPath, [wrangler, 'dev', '--config', config, '--ip', '127.0.0.1', '--port', '8790', '--persist-to', state], { env, stdio: ['ignore', 'pipe', 'pipe'] });
  server.stdout.on('data', part => { log += part; }); server.stderr.on('data', part => { log += part; });
  let ready = false;
  for (let i = 0; i < 300; i++) { if (server.exitCode !== null) throw new Error(log); try { if ((await fetch(base + '/api/me')).ok) { ready = true; break; } } catch {} await pause(100); }
  assert.ok(ready, 'Worker did not start: ' + log);
  const guest = client(), admin = client(), editor = client(), student = client();
  assert.deepEqual(await guest.request('/content'), content);
  await guest.request('/editor/draft', undefined, 401);
  const adminUser = (await admin.request('/auth/register', { username: 'admin-test', password, role: 'admin' })).user;
  assert.equal(adminUser.role, 'student');
  const editorUser = (await editor.request('/auth/register', { username: 'editor-test', password })).user;
  const studentUser = (await student.request('/auth/register', { username: 'student-test', password })).user;
  await student.request('/editor/draft', undefined, 403);
  await student.request('/admin/users', undefined, 403);
  await guest.request('/auth/login', { username: 'admin-test', password: 'Wrong-password-172!' }, 401);
  await guest.request('/auth/register', { username: 'forged-origin', password }, 403, { Origin: 'https://attacker.invalid' });
  await student.request('/editor/publish', { version: 0, content }, 403);
  await guest.request('/auth/login', { username: 'admin-test', password, oversized: 'x'.repeat(500_001) }, 413);
  sql("UPDATE users SET role='admin' WHERE username='admin-test';");
  await admin.request('/admin/role', { userId: editorUser.id, role: 'editor' }, 403, { 'X-CSRF-Token': '' });
  await admin.request('/admin/role', { userId: editorUser.id, role: 'editor' });
  await admin.request('/admin/role', { userId: adminUser.id, role: 'student' }, 409);
  assert.equal((await admin.request('/me')).user.role, 'admin');
  console.log('PASS registration, password verification, CSRF, server roles and last administrator protection');

  const replicaId = '00000000-0000-4000-8000-000000000001';
  const progressData = { selectedSystemId: content.systems[0].id, systems: { [content.systems[0].id]: { answered: 1, correct: 0, mistakes: { lesson: ['question'] }, levels: {} } } };
  await guest.request('/progress', undefined, 401);
  await student.request('/progress', { deviceId: replicaId, revision: 0, store: progressData }, 403, { 'X-CSRF-Token': '' });
  await student.request('/progress', { deviceId: replicaId, revision: 0, store: progressData, userId: adminUser.id }, 400);
  const badProgress = structuredClone(progressData); badProgress.systems[content.systems[0].id].correct = 2;
  await student.request('/progress', { deviceId: replicaId, revision: 0, store: badProgress }, 400);
  await student.request('/progress', { deviceId: replicaId, revision: 0, store: progressData });
  await student.request('/progress', { deviceId: replicaId, revision: 0, store: progressData }, 409);
  const newerProgress = structuredClone(progressData); newerProgress.systems[content.systems[0].id].answered = 2;
  await student.request('/progress', { deviceId: replicaId, revision: 1, store: newerProgress });
  await student.request('/progress', { deviceId: replicaId, revision: 2, store: progressData });
  assert.equal((await student.request('/progress'))[0].store.systems[content.systems[0].id].answered, 2);
  assert.deepEqual(await editor.request('/progress'), []); assert.deepEqual(await admin.request('/progress'), []);
  console.log('PASS account-scoped progress, CSRF, invalid counters, conflict detection and protection against stale snapshots');

  const accessOriginal = await editor.request('/editor/draft');
  const restricted = structuredClone(accessOriginal.content);
  restricted.systems[0].access = 'restricted';
  restricted.systems[0].rules.push('Nová ověřovací dohoda');
  restricted.systems[0].levels[0].test = { source: 'separate', questionCount: 2, shuffle: false, requireLesson: false, questions: restricted.systems[0].levels[0].questions.slice(0, 3).map(q => ({ ...q, id: 'independent-' + q.id })) };
  const restrictedPublished = await editor.request('/editor/publish', { version: accessOriginal.version, content: restricted });
  assert.equal((await guest.request('/content')).systems.length, content.systems.length - 1);
  assert.deepEqual((await guest.request('/content')).lockedSystems, [{ id: content.systems[0].id, name: content.systems[0].name }]);
  for (const path of ['/content/trainer.json', '/content/%74rainer.json', '/%63ontent/trainer.json', '/content%2Ftrainer.json']) {
    const response = await fetch(base + path);
    assert.equal((await response.json()).systems.some(s => s.id === content.systems[0].id), false);
  }
  const direct = await fetch(base + '/content/trainer.json');
  assert.equal((await direct.json()).systems.some(s => s.id === content.systems[0].id), false);
  await student.request('/admin/system-access', { userId: studentUser.id, systemId: content.systems[0].id, allowed: true }, 403);
  await admin.request('/admin/system-access', { userId: studentUser.id, systemId: content.systems[0].id, allowed: true }, 403, { 'X-CSRF-Token': '' });
  await admin.request('/admin/system-access', { userId: studentUser.id, systemId: content.systems[0].id, allowed: 'true' }, 400);
  await admin.request('/admin/system-access', { userId: studentUser.id, systemId: 'missing', allowed: true }, 404);
  await admin.request('/admin/system-access', { userId: editorUser.id, systemId: content.systems[0].id, allowed: false }, 400);
  await admin.request('/admin/system-access', { userId: studentUser.id, systemId: content.systems[0].id, allowed: true });
  assert.equal((await student.request('/content')).systems.length, content.systems.length);
  assert.deepEqual((await student.request('/content')).systems[0].levels[0].test, restricted.systems[0].levels[0].test);
  await admin.request('/admin/system-access', { userId: studentUser.id, systemId: content.systems[0].id, allowed: null });
  assert.equal((await student.request('/content')).systems.length, content.systems.length - 1);
  for (const system of content.systems) await admin.request('/admin/system-access', { userId: studentUser.id, systemId: system.id, allowed: false });
  assert.equal((await student.request('/content')).systems.length, 0);
  const deniedDirect = await fetch(base + '/content/trainer.json', { headers: { Cookie: student.cookie } });
  assert.equal((await deniedDirect.json()).systems.length, 0);
  assert.equal((await editor.request('/content')).systems.length, content.systems.length);
  for (const system of content.systems) await admin.request('/admin/system-access', { userId: studentUser.id, systemId: system.id, allowed: null });
  await editor.request('/editor/publish', { version: restrictedPublished.version, content: accessOriginal.content });
  console.log('PASS system access defaults, overrides, CSRF, staff permissions and direct JSON protection');

  const original = await editor.request('/editor/draft');
  const changed = structuredClone(original.content); changed.systems[0].levels[0].questions[0].prompt = 'Sdílená testovací otázka';
  const saved = await editor.request('/editor/draft', { version: original.version, content: changed });
  assert.equal((await guest.request('/content')).systems[0].levels[0].questions[0].prompt, content.systems[0].levels[0].questions[0].prompt);
  await editor.request('/editor/publish', { version: original.version, content: changed }, 409);
  const invalid = structuredClone(changed); invalid.systems[0].levels[0].questions[0].correctBid = '8NT';
  await editor.request('/editor/publish', { version: saved.version, content: invalid }, 400);
  const published = await editor.request('/editor/publish', { version: saved.version, content: changed });
  assert.equal((await guest.request('/content')).systems[0].levels[0].questions[0].prompt, 'Sdílená testovací otázka');
  const restored = await editor.request('/editor/restore', { version: published.version, restoreVersion: 0 });
  assert.equal(restored.content.systems[0].levels[0].questions[0].prompt, content.systems[0].levels[0].questions[0].prompt);
  assert.equal((await guest.request('/content')).systems[0].levels[0].questions[0].prompt, 'Sdílená testovací otázka');
  const results = await Promise.all([editor, admin].map(async actor => {
    const response = await fetch(base + '/api/editor/draft', { method: 'POST', headers: { Cookie: actor.cookie, Origin: base, 'Content-Type': 'application/json', 'X-CSRF-Token': actor.csrf }, body: JSON.stringify({ version: restored.version, content: changed }) });
    return { status: response.status, value: await response.json() };
  }));
  assert.deepEqual(results.map(result => result.status).sort(), [200, 409]);
  assert.equal(results.find(result => result.status === 200).value.version, restored.version + 1);
  assert.equal((await editor.request('/editor/history')).length, 7);
  run(['--experimental-strip-types', 'scripts/seed-database.ts', '--local']);
  assert.equal((await editor.request('/editor/draft')).version, restored.version + 1);
  console.log('PASS shared drafts, concurrent write protection, validated publication, history, restore and repeatable seed');

  const secondSession = client(); await secondSession.request('/auth/login', { username: 'STUDENT-TEST', password });
  await student.request('/auth/password', { oldPassword: password, newPassword: 'New-local-test-password-172!' });
  assert.equal((await secondSession.request('/me')).user, null);
  await guest.request('/auth/login', { username: 'student-test', password }, 401);
  await guest.request('/auth/login', { username: 'student-test', password: 'New-local-test-password-172!' });
  await guest.request('/auth/logout', {}); assert.equal((await guest.request('/me')).user, null);
  const savedPasswords = JSON.parse(sql('SELECT password_hash,password_salt FROM users;'))[0].results;
  assert.ok(savedPasswords.every(row => row.password_hash.length === 64 && row.password_hash !== password && row.password_salt !== password));
  assert.equal(new Set(savedPasswords.map(row => row.password_salt)).size, savedPasswords.length);
  console.log('PASS salted password storage, password change, session revocation and logout');

  const executablePath = process.env.CHROMIUM_PATH || ['/usr/bin/chromium', '/usr/bin/chromium-browser', '/usr/bin/google-chrome'].find(existsSync);
  assert.ok(executablePath, 'Install Chromium or set CHROMIUM_PATH.');
  browser = await chromium.launch({ executablePath, headless: true, args: ['--disable-dev-shm-usage'] });
  const context = await browser.newContext(); const page = await context.newPage(); const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(base); assert.equal(await page.getByRole('button', { name: 'Správa obsahu', exact: true }).count(), 0);
  await page.getByRole('button', { name: 'Přihlásit se', exact: true }).click();
  assert.notEqual(await page.getByRole('dialog').evaluate(node => getComputedStyle(node).backgroundColor), 'rgba(0, 0, 0, 0)', 'Account dialog must have an opaque background.');
  await page.getByLabel('Uživatelské jméno', { exact: true }).fill('editor-test'); await page.getByLabel('Heslo', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Zobrazit heslo', exact: true }).click();
  assert.equal(await page.getByLabel('Heslo', { exact: true }).getAttribute('type'), 'text');
  assert.equal(await page.getByLabel('Heslo', { exact: true }).inputValue(), password);
  await page.getByRole('button', { name: 'Skrýt heslo', exact: true }).click();
  assert.equal(await page.getByLabel('Heslo', { exact: true }).getAttribute('type'), 'password');
  await page.getByRole('dialog').getByRole('button', { name: 'Přihlásit se', exact: true }).click();
  await page.getByRole('button', { name: 'Správa obsahu', exact: true }).click();
  await page.getByRole('button', { name: 'Načíst koncept', exact: true }).click();
  await page.getByLabel('Otázka', { exact: true }).fill('Zveřejněná otázka z webového editoru');
  const backgroundContent = structuredClone(await guest.request('/content'));
  backgroundContent.title = 'Změna obsahu na pozadí';
  await page.route('**/api/content', route => route.fulfill({ json: backgroundContent }));
  await page.evaluate(() => window.dispatchEvent(new Event('focus')));
  await pause(500);
  assert.equal(await page.getByLabel('Otázka', { exact: true }).inputValue(), 'Zveřejněná otázka z webového editoru');
  await page.unroute('**/api/content');
  console.log('PASS background refresh preserves the editor unsaved draft');
  await page.getByRole('button', { name: 'Uložit koncept na server', exact: true }).click();
  await page.getByText('Koncept uložen na serveru.', { exact: false }).waitFor();
  await page.getByRole('button', { name: 'Zveřejnit pro všechny', exact: true }).click();
  await page.getByText('Zveřejněno pro všechny.', { exact: false }).waitFor();
  await page.getByRole('dialog').getByRole('button', { name: 'Zavřít', exact: true }).click();
  await page.getByRole('button', { name: 'Začít trénink', exact: true }).click();
  await page.getByRole('heading', { name: 'Zveřejněná otázka z webového editoru', exact: true }).waitFor();
  assert.equal((await guest.request('/content')).systems[0].levels[0].questions[0].prompt, 'Zveřejněná otázka z webového editoru');
  assert.deepEqual(errors, []); console.log('PASS browser login and editing/publishing visible to all players');
  const otherTab = await context.newPage(); await otherTab.goto(base);
  await otherTab.getByRole('button', { name: 'Můj účet', exact: true }).click();
  await otherTab.getByRole('button', { name: 'Odhlásit se', exact: true }).click();
  await page.getByRole('button', { name: 'Přihlásit se', exact: true }).waitFor();
  assert.equal(await page.getByRole('button', { name: 'Správa obsahu', exact: true }).count(), 0);
  console.log('PASS logout synchronizes the account across browser tabs');
  const adminContext = await browser.newContext(); const adminPage = await adminContext.newPage();
  adminPage.on('pageerror', error => errors.push(error.message));
  await adminPage.goto(base); await adminPage.getByRole('button', { name: 'Přihlásit se', exact: true }).click();
  await adminPage.getByLabel('Uživatelské jméno', { exact: true }).fill('admin-test'); await adminPage.getByLabel('Heslo', { exact: true }).fill(password);
  await adminPage.getByRole('dialog').getByRole('button', { name: 'Přihlásit se', exact: true }).click();
  await adminPage.getByRole('button', { name: 'Můj účet', exact: true }).click(); await adminPage.getByRole('button', { name: 'Načíst uživatele', exact: true }).click();
  assert.notEqual(await adminPage.getByRole('dialog').evaluate(node => getComputedStyle(node).backgroundColor), 'rgba(0, 0, 0, 0)');
  await adminPage.getByLabel('Hledat uživatele', { exact: true }).fill('STÚDENT');
  assert.equal(await adminPage.locator('.account-users li').count(), 1);
  await adminPage.getByLabel('Filtrovat podle role', { exact: true }).selectOption('editor');
  await adminPage.getByText('Žádný uživatel neodpovídá hledání.', { exact: true }).waitFor();
  await adminPage.getByLabel('Filtrovat podle role', { exact: true }).selectOption('all');
  await adminPage.getByRole('button', { name: 'Systémy uživatele student-test', exact: true }).click();
  const accessSelect = adminPage.getByLabel('Přístup k systému ' + content.systems[0].name, { exact: true });
  await accessSelect.selectOption('deny');
  await adminPage.getByRole('status').filter({ hasText: 'Přístup k systému byl uložen' }).waitFor();
  assert.equal((await student.request('/content')).systems.some(system => system.id === content.systems[0].id), false);
  await accessSelect.selectOption('default');
  await adminPage.waitForFunction(() => document.querySelector('.system-access select')?.disabled === false);
  assert.equal((await student.request('/content')).systems.length, content.systems.length);
  console.log('PASS administrator changes individual system access through the web');
  await adminPage.getByLabel('Role uživatele student-test', { exact: true }).selectOption('editor');
  await adminPage.waitForFunction(() => document.querySelector('[aria-label="Role uživatele student-test"]')?.disabled === false);
  assert.equal((await student.request('/me')).user.role, 'editor');
  await adminPage.getByLabel('Hledat uživatele', { exact: true }).fill('');
  await adminPage.locator('summary').filter({ hasText: 'Změnit heslo' }).click();
  await adminPage.getByLabel('Současné heslo', { exact: true }).fill(password);
  await adminPage.getByLabel('Nové heslo', { exact: true }).fill('Changed-admin-password-172!');
  await adminPage.getByLabel('Zopakovat nové heslo', { exact: true }).fill('Mismatch-password-172!');
  await adminPage.getByRole('button', { name: 'Uložit nové heslo', exact: true }).click();
  await adminPage.getByRole('alert').filter({ hasText: 'Nová hesla se neshodují' }).waitFor();
  await adminPage.getByLabel('Zopakovat nové heslo', { exact: true }).fill('Changed-admin-password-172!');
  await adminPage.getByRole('button', { name: 'Uložit nové heslo', exact: true }).click();
  await adminPage.getByRole('status').filter({ hasText: 'Heslo změněno' }).waitFor();
  await admin.request('/auth/login', { username: 'admin-test', password: 'Changed-admin-password-172!' });
  await adminPage.locator('summary').filter({ hasText: 'Změnit heslo' }).click();
  if (process.env.HABRA_SCREENSHOT_DIR) {
    mkdirSync(process.env.HABRA_SCREENSHOT_DIR, { recursive: true });
    await adminPage.waitForFunction(() => getComputedStyle(document.querySelector('[role="dialog"]')).opacity === '1');
    await adminPage.screenshot({ path: join(process.env.HABRA_SCREENSHOT_DIR, 'account-desktop.png') });
  }
  await adminPage.setViewportSize({ width: 390, height: 844 });
  assert.ok(await adminPage.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  assert.notEqual(await adminPage.getByRole('dialog').evaluate(node => getComputedStyle(node).backgroundColor), 'rgba(0, 0, 0, 0)');
  if (process.env.HABRA_SCREENSHOT_DIR) await adminPage.screenshot({ path: join(process.env.HABRA_SCREENSHOT_DIR, 'account-mobile.png') });
  console.log('PASS administrator assigns roles through the web and mobile account layout fits');
  const studentContext = await browser.newContext(); const studentPage = await studentContext.newPage();
  studentPage.on('pageerror', error => errors.push(error.message));
  await studentPage.goto(base); await studentPage.getByRole('button', { name: 'Přihlásit se', exact: true }).click();
  await studentPage.getByRole('button', { name: 'Vytvořit nový účet', exact: true }).click();
  await studentPage.getByLabel('Uživatelské jméno', { exact: true }).fill('web-student'); await studentPage.getByLabel('Heslo', { exact: true }).fill(password);
  await studentPage.getByLabel('Zopakovat heslo', { exact: true }).fill('Mismatch-password-172!');
  await studentPage.getByRole('button', { name: 'Vytvořit účet', exact: true }).click();
  await studentPage.getByRole('alert').filter({ hasText: 'Hesla se neshodují' }).waitFor();
  assert.equal(await studentPage.getByLabel('Uživatelské jméno', { exact: true }).inputValue(), 'web-student');
  await studentPage.getByLabel('Zopakovat heslo', { exact: true }).fill(password);
  await studentPage.getByRole('button', { name: 'Vytvořit účet', exact: true }).click();
  await studentPage.getByRole('button', { name: 'Můj účet', exact: true }).waitFor();
  assert.equal(await studentPage.getByRole('button', { name: 'Správa obsahu', exact: true }).count(), 0);
  assert.deepEqual(errors, []); console.log('PASS browser registration keeps student permissions');
  const webStudent = (await admin.request('/admin/users')).find(user => user.username === 'web-student');
  for (const system of content.systems) await admin.request('/admin/system-access', { userId: webStudent.id, systemId: system.id, allowed: false });
  await studentPage.reload();
  await studentPage.getByRole('heading', { name: 'Žádný dostupný systém', exact: true }).waitFor();
  assert.equal(await studentPage.locator('#training-system').count(), 0);
  await studentPage.getByRole('button', { name: 'Můj účet', exact: true }).click();
  await studentPage.getByRole('button', { name: 'Odhlásit se', exact: true }).click();
  await studentPage.locator('#training-system').waitFor();
  assert.equal(await studentPage.locator('#training-system option').count(), content.systems.length);
  assert.deepEqual(errors, []);
  console.log('PASS no accessible systems view and refreshed permissions after logout');
  const recoveryUserClient = client();
  const recoveryUser = (await recoveryUserClient.request('/auth/register', { username: 'recovery-user', password })).user;
  await admin.request('/admin/role', { userId: recoveryUser.id, role: 'admin' });
  await recoveryUserClient.request('/progress', { deviceId: replicaId, revision: 0, store: progressData });
  const oldSession = client(); await oldSession.request('/auth/login', { username: 'recovery-user', password });
  await guest.request('/admin/password-reset', { userId: recoveryUser.id }, 401);
  await editor.request('/admin/password-reset', { userId: recoveryUser.id }, 403);
  await admin.request('/admin/password-reset', { userId: recoveryUser.id }, 403, { 'X-CSRF-Token': '' });
  await admin.request('/admin/password-reset', { userId: 'does-not-exist' }, 404);
  const resetToken = link => new URL(link.url).hash.slice('#reset='.length);
  const resetA = await admin.request('/admin/password-reset', { userId: recoveryUser.id });
  const resetB = await admin.request('/admin/password-reset', { userId: recoveryUser.id });
  const recoveryPassword = 'New-recovery-password-172!';
  await guest.request('/auth/reset-password', { token: resetToken(resetA), newPassword: recoveryPassword }, 400);
  await guest.request('/auth/reset-password', { token: resetToken(resetB), newPassword: recoveryPassword }, 403, { Origin: 'https://attacker.invalid' });
  await guest.request('/auth/reset-password', { token: resetToken(resetB), newPassword: 'short' }, 400);
  sql(`UPDATE password_resets SET expires_at=0 WHERE user_id='${recoveryUser.id}';`);
  await guest.request('/auth/reset-password', { token: resetToken(resetB), newPassword: recoveryPassword }, 400);
  const resetC = await admin.request('/admin/password-reset', { userId: recoveryUser.id });
  const storedReset = JSON.parse(sql(`SELECT token_hash FROM password_resets WHERE user_id='${recoveryUser.id}';`))[0].results[0];
  assert.notEqual(storedReset.token_hash, resetToken(resetC));
  const attempts = await Promise.all([recoveryPassword, 'Other-recovery-password-172!'].map(newPassword => fetch(base + '/api/auth/reset-password', { method: 'POST', headers: { Origin: base, 'Content-Type': 'application/json' }, body: JSON.stringify({ token: resetToken(resetC), newPassword }) })));
  assert.deepEqual(attempts.map(response => response.status).sort(), [200, 400]);
  const winningPassword = attempts[0].status === 200 ? recoveryPassword : 'Other-recovery-password-172!';
  await guest.request('/auth/reset-password', { token: resetToken(resetC), newPassword: recoveryPassword }, 400);
  assert.equal((await oldSession.request('/me')).user, null);
  assert.equal((await recoveryUserClient.request('/me')).user, null);
  await guest.request('/auth/login', { username: 'recovery-user', password }, 401);
  const recovered = client(); await recovered.request('/auth/login', { username: 'recovery-user', password: winningPassword });
  assert.equal((await recovered.request('/me')).user.role, 'admin');
  assert.deepEqual((await recovered.request('/progress'))[0].store, progressData);
  const resetD = await admin.request('/admin/password-reset', { userId: recoveryUser.id });
  await recovered.request('/auth/password', { oldPassword: winningPassword, newPassword: recoveryPassword });
  await guest.request('/auth/reset-password', { token: resetToken(resetD), newPassword: winningPassword }, 400);
  console.log('PASS administrator recovery, CSRF, replacement/expiry, hashed tokens, single-use concurrent redemption, session revocation and preserved administrator role/progress');

  const resetAdminContext = await browser.newContext(), resetMobileContext = await browser.newContext({ viewport: { width: 320, height: 740 }, colorScheme: 'dark' });
  const resetAdminPage = await resetAdminContext.newPage();
  await resetAdminPage.goto(base); await resetAdminPage.getByRole('button', { name: 'Přihlásit se', exact: true }).click();
  await resetAdminPage.getByLabel('Uživatelské jméno', { exact: true }).fill('admin-test');
  await resetAdminPage.getByLabel('Heslo', { exact: true }).fill('Changed-admin-password-172!');
  await resetAdminPage.getByRole('dialog').getByRole('button', { name: 'Přihlásit se', exact: true }).click();
  await resetAdminPage.getByRole('button', { name: 'Můj účet', exact: true }).click();
  await resetAdminPage.getByRole('button', { name: 'Načíst uživatele', exact: true }).click();
  await resetAdminPage.getByLabel('Hledat uživatele', { exact: true }).fill('recovery-user');
  resetAdminPage.once('dialog', dialog => dialog.accept());
  await resetAdminPage.getByRole('button', { name: 'Obnovit heslo uživatele recovery-user', exact: true }).click();
  const linkField = resetAdminPage.getByLabel('Jednorázový odkaz', { exact: true }); await linkField.waitFor();
  const link = await linkField.inputValue();
  const resetMobilePage = await resetMobileContext.newPage(); await resetMobilePage.goto(link);
  await resetMobilePage.getByLabel('Nové heslo', { exact: true }).fill(recoveryPassword);
  await resetMobilePage.getByLabel('Zopakovat nové heslo', { exact: true }).fill('Mismatch-recovery-password-172!');
  await resetMobilePage.getByRole('button', { name: 'Nastavit nové heslo', exact: true }).click();
  await resetMobilePage.getByRole('alert').getByText('Hesla se neshodují.', { exact: false }).waitFor();
  assert.equal(new URL(resetMobilePage.url()).hash, '');
  assert.equal(await resetMobilePage.locator('.account-dialog').evaluate(node => node.scrollWidth <= node.clientWidth), true);
  await resetMobilePage.getByLabel('Zopakovat nové heslo', { exact: true }).fill(recoveryPassword);
  await resetMobilePage.getByRole('button', { name: 'Nastavit nové heslo', exact: true }).click();
  await resetMobilePage.getByText('Heslo bylo změněno.', { exact: false }).waitFor();
  await guest.request('/auth/reset-password', { token: resetToken({ url: link }), newPassword: recoveryPassword }, 400);
  const afterBrowserRecovery = client(); await afterBrowserRecovery.request('/auth/login', { username: 'recovery-user', password: recoveryPassword });
  assert.equal((await afterBrowserRecovery.request('/me')).user.role, 'admin');
  await resetAdminContext.close(); await resetMobileContext.close();
  console.log('PASS administrator generates recovery link through the web and mobile user sets a new password without the old password');
  const syncActor = client(); await syncActor.request('/auth/login', { username: 'editor-test', password });
  const syncKey = 'habra-progress-pages-v2:/:user:' + editorUser.id;
  const systemId = content.systems[0].id;
  const syncDesktopContext = await browser.newContext(), syncPhoneContext = await browser.newContext();
  const desktopAuth = client(), phoneAuth = client();
  await desktopAuth.request('/auth/login', { username: 'editor-test', password });
  await phoneAuth.request('/auth/login', { username: 'editor-test', password });
  const cookieFor = auth => ({ name: 'habra_session', value: auth.cookie.split('=')[1], url: base, httpOnly: true, sameSite: 'Lax' });
  await syncDesktopContext.addCookies([cookieFor(desktopAuth)]); await syncPhoneContext.addCookies([cookieFor(phoneAuth)]);
  const desktop = await syncDesktopContext.newPage(), phone = await syncPhoneContext.newPage();
  desktop.on('pageerror', error => errors.push(error.message)); phone.on('pageerror', error => errors.push(error.message));
  const legacy = { selectedSystemId: systemId, systems: { [systemId]: { answered: 2, correct: 1, levels: {}, mistakes: { [content.systems[0].levels[0].id]: [content.systems[0].levels[0].questions[0].id] } } } };
  await desktop.addInitScript(({ key, progress }) => { if (!localStorage.getItem(key)) localStorage.setItem(key, JSON.stringify(progress)); }, { key: syncKey, progress: legacy });
  const readLocal = page => page.evaluate(({ key, system }) => { const p = JSON.parse(localStorage.getItem(key))?.systems[system]; return p ? [p.answered, p.correct] : [0, 0]; }, { key: syncKey, system: systemId });
  const readRemote = async () => (await syncActor.request('/progress')).reduce((total, replica) => { const p = replica.store.systems[systemId]; return [total[0] + (p?.answered || 0), total[1] + (p?.correct || 0)]; }, [0, 0]);
  await desktop.goto(base); await desktop.getByText('Postup je synchronizovaný s účtem.', { exact: true }).waitFor();
  await eventually(readRemote, [2, 1]);
  await phone.goto(base); await phone.getByText('Postup je synchronizovaný s účtem.', { exact: true }).waitFor();
  await eventually(() => readLocal(phone), [2, 1]);
  await desktop.getByRole('button', { name: 'Začít trénink', exact: true }).click();
  await phone.getByRole('button', { name: 'Začít trénink', exact: true }).click();
  await Promise.all([desktop.getByRole('button', { name: '1♣', exact: true }).click(), phone.getByRole('button', { name: '1♣', exact: true }).click()]);
  await eventually(readRemote, [4, 3]);
  await desktop.evaluate(() => window.dispatchEvent(new Event('focus')));
  await phone.evaluate(() => window.dispatchEvent(new Event('focus')));
  await eventually(() => readLocal(desktop), [4, 3]); await eventually(() => readLocal(phone), [4, 3]);
  await phone.route('**/api/progress', route => route.abort());
  await phone.getByRole('button', { name: 'Další úloha', exact: true }).click();
  await phone.getByRole('button', { name: '1♥', exact: true }).click();
  await phone.getByRole('button', { name: '← Pozastavit', exact: true }).click();
  await phone.getByText('Spojení se serverem není dostupné.', { exact: false }).waitFor();
  await eventually(() => readLocal(phone), [5, 4]); assert.deepEqual(await readRemote(), [4, 3]);
  phone.once('dialog', dialog => dialog.accept()); await phone.reload();
  await phone.getByText('Spojení se serverem není dostupné.', { exact: false }).waitFor();
  await eventually(() => readLocal(phone), [5, 4]);
  await phone.unroute('**/api/progress'); await phone.evaluate(() => window.dispatchEvent(new Event('online')));
  await phone.getByText('Postup je synchronizovaný s účtem.', { exact: true }).waitFor();
  await eventually(readRemote, [5, 4]);
  await phone.evaluate(() => window.dispatchEvent(new Event('focus'))); await eventually(readRemote, [5, 4]);
  const twin = await syncPhoneContext.newPage(); await twin.goto(base);
  await twin.getByText('Postup je synchronizovaný s účtem.', { exact: true }).waitFor();
  await phone.getByRole('button', { name: 'Začít trénink', exact: true }).click();
  await twin.getByRole('button', { name: 'Začít trénink', exact: true }).click();
  await Promise.all([phone.getByRole('button', { name: '1♣', exact: true }).click(), twin.getByRole('button', { name: 'PASS', exact: true }).click()]);
  await eventually(readRemote, [7, 5]);
  for (const question of content.systems[0].levels[0].questions.slice(1, 3)) {
    await phone.getByRole('button', { name: 'Další úloha', exact: true }).click();
    await twin.getByRole('button', { name: 'Další úloha', exact: true }).click();
    const correct = question.type === 'choice' ? phone.locator('.choices .choice').nth(question.options.findIndex(option => option.correct)) : phone.getByRole('button', { name: question.correctBid.replace('C', '♣').replace('D', '♦').replace('H', '♥').replace('S', '♠'), exact: true });
    const wrong = question.type === 'choice' ? twin.locator('.choices .choice').nth(question.options.findIndex(option => !option.correct)) : question.correctBid === 'PASS' ? twin.locator('.bid-grid button:enabled').first() : twin.getByRole('button', { name: 'PASS', exact: true });
    await Promise.all([correct.click(), wrong.click()]);
  }
  await eventually(readRemote, [11, 7]);
  await phone.getByRole('button', { name: '← Pozastavit', exact: true }).click();
  await twin.getByRole('button', { name: '← Pozastavit', exact: true }).click();
  await eventually(() => readLocal(phone), [11, 7]); await eventually(() => readLocal(twin), [11, 7]);
  twin.once('dialog', dialog => dialog.accept());
  await twin.locator('#training-system').selectOption('epstein-precision');
  await phone.getByRole('heading', { name: content.systems[0].name + ', krok za krokem.', exact: true }).waitFor();
  await twin.getByRole('heading', { name: 'Epstein Precision, krok za krokem.', exact: true }).waitFor();
  await phone.evaluate(() => window.dispatchEvent(new Event('focus')));
  await eventually(readRemote, [11, 7]);
  await twin.close();
  await phone.getByRole('button', { name: 'Můj účet', exact: true }).click(); await phone.getByRole('button', { name: 'Odhlásit se', exact: true }).click();
  await phone.getByRole('button', { name: 'Přihlásit se', exact: true }).waitFor();
  await phone.getByRole('button', { name: 'Výsledky', exact: true }).click();
  assert.equal(await phone.locator('.stat-grid strong').first().innerText(), '0');
  await phone.getByRole('button', { name: 'Přihlásit se', exact: true }).click();
  await phone.getByLabel('Uživatelské jméno', { exact: true }).fill('editor-test'); await phone.getByLabel('Heslo', { exact: true }).fill(password);
  await phone.getByRole('dialog').getByRole('button', { name: 'Přihlásit se', exact: true }).click();
  await phone.getByText('Postup je synchronizovaný s účtem.', { exact: true }).waitFor();
  await eventually(() => readLocal(phone), [11, 7]); await eventually(readRemote, [11, 7]);
  await syncDesktopContext.close(); await syncPhoneContext.close();
  assert.deepEqual(errors, []);
  console.log('PASS two-device progress, legacy import, simultaneous answers, offline reload/retry, no double counting and guest/account isolation');
  for (let i = 0; i < 10; i++) await client().request('/auth/login', { username: 'unknown-user', password }, 401);
  await client().request('/auth/login', { username: 'unknown-user', password }, 429);
  await admin.request('/admin/role', { userId: editorUser.id, role: 'student' });
  await editor.request('/editor/draft', undefined, 403);
  console.log('PASS login throttling and immediate permission revocation');
} finally {
  if (browser) await browser.close();
  if (server && server.exitCode === null) { const ended = once(server, 'exit'); server.kill('SIGTERM'); await ended; }
  rmSync(dir, { recursive: true, force: true });
}
